Create zh_cn.lang
thexaero/Better-PVP-Translations pull request #23
Opened 2022-04-11 12:45 UTC by SolidBlock-cn

I read and improved the translations in PR #14. 

btw #20 has a typo in filename.

2022-04-11 12:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/thexaero/Better-PVP-Translations?pullRequest=23) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/thexaero/Better-PVP-Translations?pullRequest=23) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/thexaero/Better-PVP-Translations?pullRequest=23) it.</sub>

2022-04-11 12:47 UTC, SolidBlock-cn commented
btw I wonder why the ``zh_cn.lang`` in PR #14 and #20 does not exist in mod files.

2022-05-04 01:01 UTC, bluejt commented
Can you give me a can use zh_cn files

2022-05-05 09:42 UTC, thexaero commented
Sorry, I'm going to close this. I can't be dealing with a million PRs for the same language file, all of which are unfinished. Please work with #14 directly. 
The translation doesn't exist in the mod because a good one has not been made yet.

2022-05-21 12:44 UTC, SolidBlock-cn commented
So will the translations (in #14) be applied? As those translations still do not exist in current version of minimap and worldmap mod.

2022-05-22 09:13 UTC, thexaero commented
#14 is not finished yet, so it's not in the mod.

2022-05-22 09:22 UTC, SolidBlock-cn commented
So may I finish that? (I seem to have no permission to edit other's branch.)

2022-05-26 16:14 UTC, thexaero commented
Contact the PR author if you want to help them with the translations.

2022-07-11 13:35 UTC, Greg-21 commented
Since the author of the previously mentioned pull request is no longer interested in continuing to work on it for the time being, perhaps you could pick up the slack. What do you think?

2022-07-11 15:41 UTC, SolidBlock-cn commented
That's OK. I also fixed some of translations just now.

2022-07-11 17:10 UTC, thexaero commented
@SolidBlock-cn I'll make sure to go through and review the PRs soon. Reopening this one.

2022-07-31 11:17 UTC, thexaero requested changes
You've done an amazing job with the translation! One of the best ones so far.
Just reviewed the first file. Going to review the other ones after you fix the current issues.

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_initial=初始化
Does this mean "the first letters of each word"?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_potion_status=药水效果
Translates back as "potion effect", which doesn't seem correct. Should mean "potion effect status".

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_toggle_grid=区块网格开关
Does this work for "toggle chunk grid"?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_box_entity_info=一个显示准星指向的生物信息的界面，包括玩家。
Does this say "including players"? (it should)

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_entity_info_max_hearts=最大生命值
Should be "max hearts" specifically, not health.

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_entity_info_numbers=生命值
Should mean that health is shown as a number instead of hearts. Does it?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_show_full_amount=物品堆叠最大数量
Translation back seems wrong. Does this mean "show a sum of all stacks for this item"?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_make_automatic_msg2=这将在选定的世界/服务器和自动识别的世界/服务器之间交换所有的路径点数据，从而模拟自动获取路径点。修改前请确保你知道你在做什么。
Translates some of it back as "simulating automatic waypoint acquisition" which seems weird to me. Otherwise seems correct. Does it mean "simulates turning the selected non-automatic world/server into the new automatic one"?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_item_tooltip_time=显示格式
"Display For" means the time for how long the tooltip is displayed.

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_item_tooltip_time=显示格式
For example, "Display for 5 seconds".

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_multiply_msg1=此选项只用于修正不正确的坐标系
Not sure if correct. Translates back as "coordinate systems" but should just be "coordinates". Probably correct though.

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_divide_msg2=你确定你想要将§c§l所有§r§f子世界的坐标除以 8 吗？
These seem incorrect. It's not "all sub-worlds", it should be "all waypoints of the current sub-world".

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_box_cave_maps2=可以显示地面之下的地图模式，主要用来显示洞穴和建筑内部。天花板大小指的是在你的头顶上由固体方块组成的正方形天花板的大小，探测这些方块以启用洞穴模式。这些固体方块不一定是在同一个Y轴上。
Possibly incorrect. Does this say that the whole square needs to have solid blocks at every position? Translates back as "a block" for me.

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_icons_list=按下玩家列表键时
Is this not too long?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_names_list=按下玩家列表键时
Is this not too long?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_day=天数
Translates back as "number of days" or "days". Not sure if correct. When you just join a new world it says "Day 1" for the first day. Does this translation work with that?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_held_centered_position=保持物品居中时
Does this work for "positions of the currently held items in hands, when the interface is centered"?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_overlay_settings=光照叠加设置
Incorrect. This is not just for light overlay.

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_box_always_entity_nametags2=总是为相同标签的实体显示名称，无论名称设置为什么。
Weird translation back for me. Does this mean "always display names for entities who have 'name tags', regardless of the Names setting"?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +narration.xaero_ui_list_left_right_usage=按左键和邮件选择该项内的一个列
Does this say "Press LEFT and RIGHT buttons to select a column within the entry"?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_toggle_disabled=禁用
Make sure it means "enabled" and "disabled", not "enable" and "disable", which is the opposite.

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_category_settings_save_confirm_warning=警告：此配置屏幕近期被替换！
Translates back as "configuration screen" but it should be "confirmation screen". Is it correct?

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_box_radar_render_over_minimap=在小地图框架的上方渲染实体，而不是渲染在框架内。这样渲染的实体将会像路径点那样，超出范围时贴在边框处。可见的实体依然仅限于仅在游戏客户端中加载了的。\n \n 选项“玩家列表” — 仅在按下了“列举玩家”按键（默认为Tab）时渲染小地图。
Translates back as "Option "Player List" - only renders the minimap when the "List Players" button is pressed"
Make sure it says "renders over the minimap"

2022-07-31 11:17 UTC, thexaero commented on zh_cn.lang
> +gui.xaero_box_pac_players=当有与你分享了坐标（由Open Parties and Claims模组）的玩家超出小地图框架边界或因其他原因不可见时，显示这些玩家。
Should be "who are sharing their coordinates with you". Translates back weirdly.

2022-07-31 15:18 UTC, thexaero commented
I have moved the minimap lines to a separate repository, but don't worry, you can keep working on this file as a whole. I'll separate everything myself after the merge.

2022-10-24 15:12 UTC, Demonese commented
Hello [SolidBlock-cn](https://github.com/SolidBlock-cn), is there any update?

2022-10-25 04:45 UTC, SolidBlock-cn commented
> Hello [SolidBlock-cn](https://github.com/SolidBlock-cn), is there any update?
> 
> I found that after 3 months this PR hasn't been updated, so created 2 new pull request:
> 
>     * Better PVP: [add zh_cn.lang #27](https://github.com/thexaero/Better-PVP-Translations/pull/27)
> 
>     * Minimap: [add zh_cn.lang xaero-minimap-translations#2](https://github.com/thexaero/xaero-minimap-translations/pull/2)

OK I'll see that.

2022-10-25 04:46 UTC, SolidBlock-cn commented
I hope I can see the zh_cn localization when I update the mod next time.

2022-10-25 07:59 UTC, merged

2022-10-27 11:30 UTC, thaumiel9 commented
很高兴这个mod/mod作者在时隔了n久之后终于添加了zh_cn.lang，特此送上庆祝。或许我该存档我那玩笑般的存储库了。（https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation）
I'm glad that this mod/mod author finally added zh_cn.lang after a long lapse, hereby to celebrate. Maybe it's time for me to archive my joke-like repository.（https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation）

2022-10-27 12:13 UTC, Demonese commented
> 很高兴这个mod/mod作者在时隔了n久之后终于添加了zh_cn.lang，特此送上庆祝。或许我该存档我那玩笑般的存储库了。（[https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation）](https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation%EF%BC%89) I'm glad that this mod/mod author finally added zh_cn.lang after a long lapse, hereby to celebrate. Maybe it's time for me to archive my joke-like repository.（[https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation）](https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation%EF%BC%89)

你急什么，Minimap 和 World Map 还没解决。

2022-10-29 15:30 UTC, thaumiel9 commented
> > 很高兴这个mod/mod作者在时隔了n久之后终于添加了zh_cn.lang，特此送上庆祝。或许我该存档我那玩笑般的存储库了。（[https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation）](https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation%EF%BC%89) I'm glad that this mod/mod author finally added zh_cn.lang after a long lapse, hereby to celebrate. Maybe it's time for me to archive my joke-like repository.（[https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation）](https://github.com/thaumiel9/Xaeros-Mods-Chinese-Translation%EF%BC%89)
> 
> 你急什么，Minimap 和 World Map 还没解决。 You shouldn't be in such a hurry, Minimap and World Map are not merged or translate yet.

一段时间之前 Better PvP 和 Minimap 使用同一个翻译文件，我也在老的项目（这个存储库）里Pull request过。
作者因为我和他交流时使用机翻而不采取我的翻译（交流受阻），但是我发现他貌似是在用机翻来检查翻译，于是就不欢而散了。
自此之后我就自己业余翻译，不再考虑Pull request。Minimap 和 World Map 我都有很及时的做更新。但是我累了，不想继续了，所以我看到 Minimap 添加了zh_cn.lang就很高兴，我不用继续做着无用的工作了。
（顺便一提，我的翻译不是机翻，每次有新的文本我都会查wiki确定正确的译名，对文本进行本土化和易读性优化，会认真的校对以及润色）
唯一伤心的就是，费尽心力的免费劳动被贬得一文不值。

Some time ago Better PvP and Minimap use the same translation file, I also pull request in the old project (this repository).
The author refused to take my translation because I used machine translation when I communicated with him (communication was blocked), but I found out that he seemed to be using machine translation to check the translation, so I broke up.
Since then, I have translated as an amateur and no longer consider pull requests. I have updated Minimap and World Map very timely. But I'm tired and don't want to continue, so I'm glad to see zh_cn.lang added to Minimap, I don't have to continue doing useless work.
(By the way, my translation is not machine translation. Every time there is a new text, I will check the wiki to determine the correct translation name, localize and optimize the text for readability, and will carefully proofread and polish)
The only sad thing is that the painstaking free labor is reduced to nothing.

2022-10-29 18:16 UTC, thexaero commented
@thaumiel9 I am very sorry that I care about the quality of the translation. I don't care if somebody uses machine translation as a base. That was not the problem. If I can't properly communicate with you, I can't discuss any potential mistakes in the actual meaning of the lines. We tried and it was absolutely hopeless. Mistakes in the meaning of the lines have happened in every single translation ever and have nothing to do with how good your grammar was. I don't expect people to 100% understand everything about the mod. That's what I'm here for.